Added index.html
semih1239/hyf-homework pull request #6
Opened 2021-05-09 20:55 UTC by semih1239

2021-05-11 10:23 UTC, FrederikNygart requested changes
Nice work Semih, I have a good amount of comments, but overall i would say you understand the primary concepts of all these exercises. 

Let me know if you need help with any of my comments.

2021-05-11 10:23 UTC, FrederikNygart commented on javascript/javascript1/week2/script.js
> +let days = ['Sunday','Monday','Tuesday','Wednesday','Thursday','Friday','Saturday']
will this ever change? consider another declaration option.

2021-05-11 10:23 UTC, FrederikNygart commented on javascript/javascript1/week2/script.js
> +    return console.log(days[today.getDay()])
Interesting idea to just use the date api instead of remainder suggestion.

Unfortunately this will not work.

let's take today as an example(tuesday the 11th of may). Get date will return 11 as a result. Given 'number' is set to 2 we will increment the date by 13 days ending up with a **Monday** instead of the requested **Thursday** - _ as 2 days from now it will be thursday_.

also you should not return console.log() statements. console.log is used to console output(for debugging) while return statements are returning a value for you to use further on. 

You could perhaps instead change it to this:

```js
console.log(getEventWeekdays(2))
```

now we console log the **returned** result of the function.

2021-05-11 10:23 UTC, FrederikNygart commented on javascript/javascript1/week2/script.js
> +function whatAmIWear(temp){
From the name 'What am i wear' it is difficult to understand the intention of the function. 

Your function should inform about 'what' it does. In this case i would say it: 'gets appropriate clothing by tempurature in celsius'.

This what you need to communicate to other people who potentially wants to use your code(and to yourself 3 months from now, when you have forgotten everything you ever knew about this code - trust me it will happen 🤕 )

TLDR;

maybe consider this name: getClothesToWear(temperatureInCelsius)

2021-05-11 10:23 UTC, FrederikNygart commented on javascript/javascript1/week2/script.js
> +        console.log('Shorts and T-shirt')
return the result instead of logging

2021-05-11 10:23 UTC, FrederikNygart commented on javascript/javascript1/week2/script.js
> +whatAmIWear(-20)
console log the result

2021-05-11 10:23 UTC, FrederikNygart commented on javascript/javascript1/week2/script.js
> +    if (studentName == 'Margrethe') {
couldn't many have the name Margrethe(maybe we need to be more specific)

2021-05-11 10:23 UTC, FrederikNygart commented on javascript/javascript1/week2/script.js
> +    return console.log('Lord ' + fullname1 + ' ' + fullname2)
return value instead of console.log

2021-05-11 10:23 UTC, FrederikNygart commented on javascript/javascript1/week2/script.js
> +getFullname(name1,name2,useFormalName)
log result

2021-05-11 10:23 UTC, FrederikNygart commented on javascript/javascript1/week2/script.js
> +    return console.log(fullname1 + ' ' + fullname2)
return value instead of console.log

2021-05-11 10:23 UTC, FrederikNygart commented on javascript/javascript1/week2/script.js
> +    else if (class18Students.indexOf(studentName) != (-1)) {
no need for parentheses around -1

2021-05-11 10:23 UTC, FrederikNygart commented on javascript/javascript1/week2/script.js
> +    else{
redundant else block

2021-05-11 10:23 UTC, FrederikNygart commented on javascript/javascript1/week2/script.js
> +    else if(studentName==''){
what if i call your function with the following values:
```js
addStudentToClass(null) // adds null
addStudentToClass() //adds undefined
addStudentToClass(' ') //adds empty string
```

and - bonus question - what if i call your function with a number or boolean value?

2021-05-11 10:23 UTC, FrederikNygart commented on javascript/javascript1/week2/script.js
> +canBuyMoreCandy()
good job!

2021-05-12 22:18 UTC, semih1239 commented
> Nice work Semih, I have a good amount of comments, but overall i would say you understand the primary concepts of all these exercises.
> 
> Let me know if you need help with any of my comments.

Hi . I updated all homeworks. Thank your very much for your feedbacks. 👍

2021-05-14 19:55 UTC, merged